### PR TITLE
Remove wasm support

### PR DESCRIPTION
**Pull request by cberner**

### CODE REVIEW

**Comment by rom1v** [comment]
Why?

**Comment by cberner** [comment]
I don't have much time to work on this crate anymore, and so am making it as easy to maintain as possible. wasm support adds complexity and has no tests.

**Comment by rom1v** [comment]
OK. 😞 

FYI I use this project is a prototype to transmit live video, which has both a desktop and wasm version, raptorq works fine for wasm.

**Comment by rom1v** [comment]
> I think you should still be able to use it for that.

Oh, I upgraded to 1.8.0, and indeed it still works :tada: (I just call raptorq from my Rust code like any other library).

**Pull request merged**
